buttons added
swastika0015/Radiant-UI pull request #6
Opened 2022-02-10 19:01 UTC by swstica

2022-02-10 19:12 UTC, iprankurpandey approved these changes

2022-02-10 19:15 UTC, prankurpandeyy commented
looks good to me .

2022-02-10 19:15 UTC, iprankurpandey commented
looks good to me .

2022-02-10 20:18 UTC, mehulsatardekar requested changes

2022-02-10 20:18 UTC, mehulsatardekar commented on buttons/button.html
> +    <title>Document</title>
Change the title to Buttons.

2022-02-10 20:18 UTC, mehulsatardekar commented on buttons/button.html
> +            <a class="nav-heading" href="../index.html"><img src="../images/logo.png"></a>
Add an alt attribute on images for alternate text.

2022-02-10 20:19 UTC, mehulsatardekar approved these changes
good to merge after the changes🚀

2022-02-10 20:20 UTC, Shivani-1524 requested changes

2022-02-10 20:20 UTC, Shivani-1524 commented on buttons/button.css
> +.button{
highly recommended to add a hover effect to your button components

2022-02-10 20:20 UTC, Shivani-1524 commented on buttons/button.css
> +.button{
also change the cursor to a pointer on hover to tell the user its a clickable element

2022-02-10 20:20 UTC, Shivani-1524 commented on buttons/button.html
> +                <iframe class="iframe"
Try fixing the responsiveness of your code iframe. feel free to ping me if you need help regarding this :)

2022-02-10 20:34 UTC, swastika0015 commented on buttons/button.html
> +                <iframe class="iframe"
Done, thanks.

2022-02-10 20:35 UTC, swastika0015 commented on buttons/button.css
> +.button{
Done, thanks.

2022-02-10 20:35 UTC, swstica commented on buttons/button.html
> +            <a class="nav-heading" href="../index.html"><img src="../images/logo.png"></a>
Will do, thanks

2022-02-10 20:35 UTC, swstica commented on buttons/button.html
> +    <title>Document</title>
done

2022-02-10 20:42 UTC, swastika0015 commented on buttons/button.html
> +                <iframe class="iframe"
Sure, thank you:)

2022-02-10 20:48 UTC, merged

2022-02-11 05:45 UTC, yaswanthmyneni commented on buttons/button.html
> +                <div><button class="button-float button-warning"><i class="fa fa-trash fa-2x"></i></button></div>
you can give a box-shadow property for floating buttons.